### ISSUE TITLE
Ветвление

### ISSUE THREAD

**Issue by avdeev** [karambafe/forGoPromo#2]
Есть несколько моделей ветвления. Самой удачной считается Git Flow. Подробнее тут:
https://habrahabr.ru/post/106912/
http://danielkummer.github.io/git-flow-cheatsheet/index.ru_RU.html

Для твоего случая я бы сделал так. Разработка идёт в ветке gh-pages, в ветку master всё сливается в конце каждой итерации.

**Comment by karambafe** [comment]
Понятно, спасибо.
Для репозитария с резиновой вертской все так переделал. Сделал merge в мастер ветку.
По данному репозитарию вообще путанница какая-то. Вроде лишние ветки удалил, merge сделал, но в истории хрень какая-то

**Comment by avdeev** [comment]
История есть история, её уже не надо править, пусть будет так.

**Comment by karambafe** [comment]
Ок :)
