### ISSUE TITLE
Убрать большие файлы из репозитория

### ISSUE THREAD

**Issue by avdeev** [karambafe/forGoPromo#3]
В репозитории должны лежать только исходники (текст, небольшиt файлы ресурсов). Все связанные файлы (макет, ещё что-то) можно положить отдельно (на гугл диск, например) и дать на них ссылки в файле README.md.

Вот тут пример работы с README.md:
https://github.com/avdeev/snake-game

**Comment by karambafe** [comment]
Макет перенесен на гугл диск, соответствующий комментарий оставлен в файлу readme.md
